"use client";

/**
 * /about – Limitations & Scope page
 * Phase 1: full content as specified in Phase 5 requirements.
 */
import Link from "next/link";

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* ── Header ── */}
      <header className="bg-gradient-to-r from-purple-600 to-blue-600 text-white px-8 py-4 flex items-center justify-between">
        <Link href="/" className="font-bold text-lg tracking-tight">
          🎵 Gaana Discovery AI
        </Link>
        <nav className="flex gap-6 text-sm text-white/80">
          <Link href="/reviews" className="hover:text-white transition-colors">
            Reviews
          </Link>
          <Link href="/discovery" className="hover:text-white transition-colors">
            Discovery
          </Link>
          <Link href="/about" className="text-white font-semibold">
            About
          </Link>
        </nav>
      </header>

      <main className="container mx-auto px-4 py-12 max-w-3xl">
        <h1 className="text-3xl font-bold mb-2">About & Limitations</h1>
        <p className="text-gray-500 mb-10">
          Transparency about what this project is, how it works, and what it
          doesn&apos;t do.
        </p>

        {/* ── Disclaimer ── */}
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6 mb-8">
          <h2 className="text-lg font-semibold text-amber-800 mb-2">
            ⚠️ Important Disclaimer
          </h2>
          <p className="text-amber-700 text-sm leading-relaxed">
            This MVP uses publicly available metadata, search results, or sample
            catalog data to demonstrate the AI-powered discovery experience. It
            does <strong>not</strong> represent Gaana&apos;s full internal
            catalog, internal listening data, or any proprietary systems.
          </p>
        </div>

        {/* ── Sections ── */}
        <div className="space-y-8">
          {/* Data Sources */}
          <section>
            <h2 className="text-xl font-semibold mb-3">📊 Data Sources</h2>
            <ul className="list-disc list-inside text-gray-600 text-sm space-y-2">
              <li>
                <strong>Reviews:</strong> Publicly available Google Play Store
                reviews fetched via the google-play-scraper package or uploaded
                via CSV.
              </li>
              <li>
                <strong>Music Metadata:</strong> Sample catalog data used for
                demonstration only — not sourced from Gaana&apos;s internal
                systems.
              </li>
              <li>
                <strong>AI Inference:</strong> All analysis and recommendations
                are generated by the{" "}
                <a
                  href="https://console.groq.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-purple-600 hover:underline"
                >
                  Groq API
                </a>{" "}
                (Mixtral / LLaMA models). Results may vary between runs.
              </li>
            </ul>
          </section>

          {/* Privacy */}
          <section>
            <h2 className="text-xl font-semibold mb-3">🔒 Privacy & Data Protection</h2>
            <ul className="list-disc list-inside text-gray-600 text-sm space-y-2">
              <li>
                All review text is processed through a PII-removal pipeline
                before being sent to the AI (emails, phone numbers, and
                usernames are masked).
              </li>
              <li>
                No review data is stored permanently — all data lives in-memory
                for the session only and is cleared on refresh.
              </li>
              <li>All API communication is over HTTPS/TLS.</li>
              <li>
                No personal listening history or user accounts are collected or
                tracked.
              </li>
            </ul>
          </section>

          {/* Scope */}
          <section>
            <h2 className="text-xl font-semibold mb-3">🎯 Project Scope</h2>
            <ul className="list-disc list-inside text-gray-600 text-sm space-y-2">
              <li>
                Built as a <strong>learning and demonstration MVP</strong> — not
                intended for production use.
              </li>
              <li>
                Music catalog coverage is limited to sample metadata; actual
                Gaana catalog is not integrated.
              </li>
              <li>
                Personalisation is based on stated preferences only (mood,
                language, activity) — no listening history is available.
              </li>
              <li>
                Review analysis accuracy depends on the quality and volume of
                reviews provided.
              </li>
              <li>
                AI recommendations may occasionally miss nuance in regional
                language preferences.
              </li>
            </ul>
          </section>

          {/* Tech Stack */}
          <section>
            <h2 className="text-xl font-semibold mb-3">🛠 Tech Stack</h2>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
              {[
                { label: "Frontend", value: "Next.js 14 + Tailwind CSS" },
                { label: "Backend", value: "Node.js + Express" },
                { label: "AI Engine", value: "Groq API (Mixtral)" },
                { label: "Frontend Hosting", value: "Vercel" },
                { label: "Backend Hosting", value: "Railway" },
                { label: "Data Sources", value: "Google Play + CSV" },
              ].map((item) => (
                <div
                  key={item.label}
                  className="bg-white border border-gray-200 rounded-xl p-3"
                >
                  <p className="text-xs text-gray-400">{item.label}</p>
                  <p className="text-sm font-medium text-gray-800 mt-0.5">
                    {item.value}
                  </p>
                </div>
              ))}
            </div>
          </section>
        </div>

        <div className="mt-12 text-center">
          <Link
            href="/"
            className="inline-block bg-purple-600 hover:bg-purple-700 text-white px-6 py-3 rounded-xl font-semibold transition-colors"
          >
            ← Back to Home
          </Link>
        </div>
      </main>
    </div>
  );
}
